# Generated by Django 5.0.4 on 2025-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('deep_cleaning', 'Deep Cleaning'), ('move_in_out', 'Move-in / Move-out'), ('floor_care', 'Floor Care')], max_length=50)),
                ('rooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.TextField()),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
